################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Startup \
Core/lvgl/porting \
Core/lvgl/src/core \
Core/lvgl/src/debugging/monkey \
Core/lvgl/src/debugging/sysmon \
Core/lvgl/src/debugging/test \
Core/lvgl/src/debugging/vg_lite_tvg \
Core/lvgl/src/display \
Core/lvgl/src/draw/convert/helium \
Core/lvgl/src/draw/convert \
Core/lvgl/src/draw/convert/neon \
Core/lvgl/src/draw/dma2d \
Core/lvgl/src/draw/espressif/ppa \
Core/lvgl/src/draw/eve \
Core/lvgl/src/draw \
Core/lvgl/src/draw/nanovg \
Core/lvgl/src/draw/nema_gfx \
Core/lvgl/src/draw/nxp/g2d \
Core/lvgl/src/draw/nxp/pxp \
Core/lvgl/src/draw/opengles \
Core/lvgl/src/draw/renesas/dave2d \
Core/lvgl/src/draw/sdl \
Core/lvgl/src/draw/snapshot \
Core/lvgl/src/draw/sw/blend \
Core/lvgl/src/draw/sw/blend/neon \
Core/lvgl/src/draw/sw/blend/riscv_v \
Core/lvgl/src/draw/sw \
Core/lvgl/src/draw/vg_lite \
Core/lvgl/src/drivers/display/drm \
Core/lvgl/src/drivers/display/fb \
Core/lvgl/src/drivers/display/ft81x \
Core/lvgl/src/drivers/display/ili9341 \
Core/lvgl/src/drivers/display/lcd \
Core/lvgl/src/drivers/display/nv3007 \
Core/lvgl/src/drivers/display/nxp_elcdif \
Core/lvgl/src/drivers/display/renesas_glcdc \
Core/lvgl/src/drivers/display/st7735 \
Core/lvgl/src/drivers/display/st7789 \
Core/lvgl/src/drivers/display/st7796 \
Core/lvgl/src/drivers/display/st_ltdc \
Core/lvgl/src/drivers/draw/eve \
Core/lvgl/src/drivers/evdev \
Core/lvgl/src/drivers/libinput \
Core/lvgl/src/drivers/nuttx \
Core/lvgl/src/drivers/opengles/assets \
Core/lvgl/src/drivers/opengles/glad/src \
Core/lvgl/src/drivers/opengles \
Core/lvgl/src/drivers/opengles/opengl_shader \
Core/lvgl/src/drivers/qnx \
Core/lvgl/src/drivers/sdl \
Core/lvgl/src/drivers/uefi \
Core/lvgl/src/drivers/wayland \
Core/lvgl/src/drivers/windows \
Core/lvgl/src/drivers/x11 \
Core/lvgl/src/font/binfont_loader \
Core/lvgl/src/font/fmt_txt \
Core/lvgl/src/font/font_manager \
Core/lvgl/src/font/imgfont \
Core/lvgl/src/font \
Core/lvgl/src/indev \
Core/lvgl/src/layouts/flex \
Core/lvgl/src/layouts/grid \
Core/lvgl/src/layouts \
Core/lvgl/src/libs/FT800-FT813 \
Core/lvgl/src/libs/barcode \
Core/lvgl/src/libs/bin_decoder \
Core/lvgl/src/libs/bmp \
Core/lvgl/src/libs/ffmpeg \
Core/lvgl/src/libs/freetype \
Core/lvgl/src/libs/frogfs/src \
Core/lvgl/src/libs/fsdrv \
Core/lvgl/src/libs/gif \
Core/lvgl/src/libs/gltf/gltf_environment \
Core/lvgl/src/libs/gltf/gltf_view/assets \
Core/lvgl/src/libs/gltf/math \
Core/lvgl/src/libs/gstreamer \
Core/lvgl/src/libs/libjpeg_turbo \
Core/lvgl/src/libs/libpng \
Core/lvgl/src/libs/libwebp \
Core/lvgl/src/libs/lodepng \
Core/lvgl/src/libs/lz4 \
Core/lvgl/src/libs/nanovg \
Core/lvgl/src/libs/qrcode \
Core/lvgl/src/libs/rle \
Core/lvgl/src/libs/rlottie \
Core/lvgl/src/libs/svg \
Core/lvgl/src/libs/tiny_ttf \
Core/lvgl/src/libs/tjpgd \
Core/lvgl/src/libs/vg_lite_driver/VGLite \
Core/lvgl/src/libs/vg_lite_driver/VGLiteKernel \
Core/lvgl/src/libs/vg_lite_driver/lv_vg_lite_hal \
Core/lvgl/src \
Core/lvgl/src/misc/cache/class \
Core/lvgl/src/misc/cache/instance \
Core/lvgl/src/misc/cache \
Core/lvgl/src/misc \
Core/lvgl/src/osal \
Core/lvgl/src/others/file_explorer \
Core/lvgl/src/others/fragment \
Core/lvgl/src/others/translation \
Core/lvgl/src/stdlib/builtin \
Core/lvgl/src/stdlib/clib \
Core/lvgl/src/stdlib \
Core/lvgl/src/stdlib/micropython \
Core/lvgl/src/stdlib/rtthread \
Core/lvgl/src/stdlib/uefi \
Core/lvgl/src/themes/default \
Core/lvgl/src/themes \
Core/lvgl/src/themes/mono \
Core/lvgl/src/themes/simple \
Core/lvgl/src/tick \
Core/lvgl/src/widgets/3dtexture \
Core/lvgl/src/widgets/animimage \
Core/lvgl/src/widgets/arc \
Core/lvgl/src/widgets/arclabel \
Core/lvgl/src/widgets/bar \
Core/lvgl/src/widgets/button \
Core/lvgl/src/widgets/buttonmatrix \
Core/lvgl/src/widgets/calendar \
Core/lvgl/src/widgets/canvas \
Core/lvgl/src/widgets/chart \
Core/lvgl/src/widgets/checkbox \
Core/lvgl/src/widgets/dropdown \
Core/lvgl/src/widgets/gif \
Core/lvgl/src/widgets/image \
Core/lvgl/src/widgets/imagebutton \
Core/lvgl/src/widgets/ime \
Core/lvgl/src/widgets/keyboard \
Core/lvgl/src/widgets/label \
Core/lvgl/src/widgets/led \
Core/lvgl/src/widgets/line \
Core/lvgl/src/widgets/list \
Core/lvgl/src/widgets/lottie \
Core/lvgl/src/widgets/menu \
Core/lvgl/src/widgets/msgbox \
Core/lvgl/src/widgets/objx_templ \
Core/lvgl/src/widgets/property \
Core/lvgl/src/widgets/roller \
Core/lvgl/src/widgets/scale \
Core/lvgl/src/widgets/slider \
Core/lvgl/src/widgets/span \
Core/lvgl/src/widgets/spinbox \
Core/lvgl/src/widgets/spinner \
Core/lvgl/src/widgets/switch \
Core/lvgl/src/widgets/table \
Core/lvgl/src/widgets/tabview \
Core/lvgl/src/widgets/textarea \
Core/lvgl/src/widgets/tileview \
Core/lvgl/src/widgets/win \
Drivers/STM32F4xx_HAL_Driver/Src \
FATFS/App \
FATFS/Target \
Middlewares/Third_Party/FatFs/src \
Middlewares/Third_Party/FatFs/src/option \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 \
Middlewares/Third_Party/FreeRTOS/Source \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang \

